"""
GUI_OVERLAY/THEME.PY  --  The Mirror of Kalandra look, in one place. (W3-01)

Single source of truth for the app's visual identity: the gold-leaf palette,
gem accents (ruby / sapphire / emerald / diamond), the shared Qt stylesheet,
and painter helpers for the ornate golden frame and cut-gem shapes.

Design rules:
  * Palette + stylesheet generation are PURE PYTHON — importable with no PyQt
    installed (so tests and headless tools can audit them).
  * Anything that paints imports PyQt lazily inside the function.
  * Every window/dialog in the app should call `theme.apply(widget)` (or embed
    `kalandra_qss()` in its stylesheet) instead of defining local colors.
  * Missing art never breaks anything: painter helpers draw procedural gold
    and gems; the future asset kit (W3-03) only *upgrades* the look.

Usage:
    from gui_overlay import theme
    theme.apply(dialog)                        # full themed stylesheet
    theme.apply(dialog, extra="QLabel{...}")   # + widget-specific rules

    # Gem-accented buttons (ruby=danger/close, emerald=confirm, sapphire=info,
    # diamond=neutral highlight):
    btn.setProperty("gem", "ruby"); btn.style().unpolish(btn); btn.style().polish(btn)

    # Custom paintEvent chrome (W3-02 KalandraWindow uses this):
    theme.paint_ornate_frame(painter, self.rect())
"""

# ---------------------------------------------------------------------------
# 1. PALETTE — gold leaf, obsidian glass, and the four gems
# ---------------------------------------------------------------------------

# Gold (the mirror's frame)
GOLD        = "#c8aa6e"   # classic PoE gold-leaf (headers, selected states)
GOLD_LIGHT  = "#f0d9a8"   # polished highlight edge
GOLD_DARK   = "#8a6d3b"   # recessed/engraved gold
GOLD_GLOW   = "#ffe9b8"   # hover/focus glow

# Obsidian glass backgrounds (darkest -> raised)
BG0   = "#0c0e12"         # window base
BG1   = "#14181f"         # panels / cards
BG2   = "#1b212b"         # raised controls
BG3   = "#232b38"         # hover surface

# Text
TEXT  = "#e8e6df"         # parchment white
MUTED = "#9aa4b2"         # steel grey
FAINT = "#7d8694"         # hints / fine print

# The gems
RUBY      = "#c03848"; RUBY_LIGHT      = "#e87284"
SAPPHIRE  = "#3868c0"; SAPPHIRE_LIGHT  = "#7aa2e8"
EMERALD   = "#2f9e68"; EMERALD_LIGHT   = "#72d6a4"
DIAMOND   = "#dce8f4"; DIAMOND_LIGHT   = "#ffffff"

# Legacy accent kept for continuity with older tabs (reads as "arcane")
TEAL = "#3fb6b6"

GEMS = {
    "ruby":     (RUBY, RUBY_LIGHT),
    "sapphire": (SAPPHIRE, SAPPHIRE_LIGHT),
    "emerald":  (EMERALD, EMERALD_LIGHT),
    "diamond":  (DIAMOND, DIAMOND_LIGHT),
}

# Semantic aliases — use these in feature code, not raw hex.
COLOR_DANGER  = RUBY
COLOR_OK      = EMERALD
COLOR_INFO    = SAPPHIRE
COLOR_NEUTRAL = DIAMOND
COLOR_WARN    = "#e0b050"

# Currency-orb tints for iconography (procedural fallbacks; W3-03 art kit
# replaces these with real sprites).
ORB_TINTS = {
    "divine": "#f5e19a", "exalted": "#e8d27a", "chaos": "#c9a86a",
    "regal": "#8fb8e8", "vaal": "#b03040", "alchemy": "#d8b84a",
    "chance": "#7a9e6a", "annulment": "#c8d4e0", "augmentation": "#88b0d0",
    "transmutation": "#6a90c0", "gold": "#e8c840",
}


# ---------------------------------------------------------------------------
# 2. THE SHARED STYLESHEET
# ---------------------------------------------------------------------------

def _gold_border(width=1):
    return f"{width}px solid {GOLD_DARK}"


def kalandra_qss(font_px=13):
    """The app-wide stylesheet. Pure string building — safe with no PyQt."""
    return f"""
/* ===== Kalandra theme (generated by gui_overlay/theme.py — do not fork) ===== */

QWidget {{ background:{BG0}; color:{TEXT}; font-size:{font_px}px; }}
QDialog {{ background:{BG0}; color:{TEXT}; }}

/* -- Text ---------------------------------------------------------------- */
QLabel {{ color:{TEXT}; background:transparent; }}
QLabel#title {{
    color:{GOLD}; font-size:{font_px + 7}px; font-weight:bold; letter-spacing:1px;
}}
QLabel#subtitle {{ color:{MUTED}; font-size:{font_px - 1}px; }}
QLabel#goldleaf {{
    color:{GOLD}; font-size:{font_px + 3}px; font-weight:bold;
    border-bottom:1px solid {GOLD_DARK}; padding-bottom:3px;
}}
QLabel#hint {{ color:{FAINT}; font-size:{font_px - 3}px; }}

/* -- Buttons: engraved gold --------------------------------------------- */
QPushButton {{
    background:qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 {BG3}, stop:1 {BG2});
    color:{TEXT};
    border:{_gold_border()};
    border-radius:6px;
    padding:7px 14px;
}}
QPushButton:hover {{
    border-color:{GOLD};
    color:{GOLD_LIGHT};
    background:qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #2b3444, stop:1 {BG3});
}}
QPushButton:pressed {{ background:{BG1}; border-color:{GOLD_DARK}; }}
QPushButton:disabled {{ color:{FAINT}; border-color:#2a313d; background:{BG1}; }}
QPushButton:focus {{ border-color:{GOLD}; outline:none; }}

/* Gem-accented buttons: btn.setProperty("gem", "ruby"|"sapphire"|"emerald"|"diamond") */
QPushButton[gem="ruby"]     {{ border:1px solid {RUBY};     color:{RUBY_LIGHT}; }}
QPushButton[gem="ruby"]:hover     {{ background:#3a2028; border-color:{RUBY_LIGHT}; }}
QPushButton[gem="sapphire"] {{ border:1px solid {SAPPHIRE}; color:{SAPPHIRE_LIGHT}; }}
QPushButton[gem="sapphire"]:hover {{ background:#20283a; border-color:{SAPPHIRE_LIGHT}; }}
QPushButton[gem="emerald"]  {{ border:1px solid {EMERALD};  color:{EMERALD_LIGHT}; }}
QPushButton[gem="emerald"]:hover  {{ background:#20342a; border-color:{EMERALD_LIGHT}; }}
QPushButton[gem="diamond"]  {{ border:1px solid {DIAMOND};  color:{DIAMOND_LIGHT}; font-weight:bold; }}
QPushButton[gem="diamond"]:hover  {{ background:#2a3038; border-color:{DIAMOND_LIGHT}; }}

/* -- Tabs: jeweled ------------------------------------------------------- */
QTabWidget::pane {{ border:1px solid {GOLD_DARK}; background:{BG1}; border-radius:4px; }}
QTabBar::tab {{
    background:{BG1}; color:{MUTED}; padding:9px 16px; margin-right:2px;
    border:1px solid #232a35; border-bottom:none;
    border-top-left-radius:6px; border-top-right-radius:6px;
}}
QTabBar::tab:selected {{
    background:qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #262e3c, stop:1 {BG2});
    color:{GOLD}; border-color:{GOLD_DARK}; border-top:2px solid {GOLD};
}}
QTabBar::tab:hover {{ color:{GOLD_LIGHT}; }}

/* -- Inputs --------------------------------------------------------------- */
QLineEdit, QPlainTextEdit, QTextEdit {{
    background:#0a0d11; color:{TEXT};
    border:1px solid #3a4150; border-radius:4px; padding:4px;
    selection-background-color:{GOLD_DARK}; selection-color:{TEXT};
}}
QLineEdit:focus, QPlainTextEdit:focus, QTextEdit:focus {{ border-color:{GOLD}; }}

QComboBox {{
    background:{BG2}; color:{TEXT}; padding:4px 8px;
    border:{_gold_border()}; border-radius:4px;
}}
QComboBox:hover {{ border-color:{GOLD}; }}
QComboBox::drop-down {{ border:none; width:22px; }}
QComboBox QAbstractItemView {{
    background:{BG1}; color:{TEXT}; border:1px solid {GOLD_DARK}; outline:none;
    selection-background-color:{GOLD_DARK}; selection-color:{GOLD_LIGHT};
}}

QCheckBox {{ color:{TEXT}; background:transparent; spacing:6px; }}
QCheckBox::indicator {{
    width:14px; height:14px; border:1px solid {GOLD_DARK};
    border-radius:3px; background:#0a0d11;
}}
QCheckBox::indicator:hover {{ border-color:{GOLD}; }}
/* ON = unmistakable: LIGHTER square + a real gold checkmark. */
QCheckBox::indicator:checked {{
    background:#3a4658; border-color:{GOLD_LIGHT};
    image: url(gui_overlay/assets/theme/check.png);
}}

/* -- Lists / tables -------------------------------------------------------- */
QListWidget {{
    background:{BG1}; color:{TEXT}; border:1px solid #2a313d; border-radius:4px;
}}
QListWidget::item {{ padding:4px 6px; }}
QListWidget::item:selected {{ background:{GOLD_DARK}; color:{GOLD_LIGHT}; }}
QListWidget::item:hover {{ background:{BG3}; }}

QTableWidget {{
    background:{BG1}; color:{TEXT}; gridline-color:#242c38;
    border:1px solid #2a313d; border-radius:4px;
    selection-background-color:{GOLD_DARK}; selection-color:{GOLD_LIGHT};
}}
QHeaderView::section {{
    background:{BG2}; color:{GOLD}; padding:5px 8px;
    border:none; border-bottom:1px solid {GOLD_DARK}; font-weight:bold;
}}
QTableCornerButton::section {{ background:{BG2}; border:none; }}

/* -- Scrollbars: thin gold rails ------------------------------------------ */
QScrollBar:vertical {{ background:{BG0}; width:11px; margin:0; }}
QScrollBar::handle:vertical {{
    background:{GOLD_DARK}; border-radius:5px; min-height:24px;
}}
QScrollBar::handle:vertical:hover {{ background:{GOLD}; }}
QScrollBar:horizontal {{ background:{BG0}; height:11px; margin:0; }}
QScrollBar::handle:horizontal {{
    background:{GOLD_DARK}; border-radius:5px; min-width:24px;
}}
QScrollBar::handle:horizontal:hover {{ background:{GOLD}; }}
QScrollBar::add-line, QScrollBar::sub-line {{ width:0; height:0; }}
QScrollBar::add-page, QScrollBar::sub-page {{ background:transparent; }}

/* -- Frames / cards --------------------------------------------------------- */
QFrame#card {{
    background:{BG1}; border:1px solid {GOLD_DARK}; border-radius:10px;
}}
QFrame#panel {{ background:{BG1}; border:1px solid #2a313d; border-radius:6px; }}
QGroupBox {{
    border:1px solid {GOLD_DARK}; border-radius:6px; margin-top:10px;
    color:{GOLD}; font-weight:bold;
}}
QGroupBox::title {{ subcontrol-origin:margin; left:10px; padding:0 4px; }}
QSplitter::handle {{ background:{GOLD_DARK}; }}

/* -- Menus / tooltips / message boxes -------------------------------------- */
QMenu {{ background:{BG1}; color:{TEXT}; border:1px solid {GOLD_DARK}; }}
QMenu::item:selected {{ background:{GOLD_DARK}; color:{GOLD_LIGHT}; }}
QToolTip {{
    background:{BG1}; color:{GOLD_LIGHT}; border:1px solid {GOLD};
    padding:4px 8px;
}}
QMessageBox {{ background:{BG1}; }}
QMessageBox QLabel {{ color:{TEXT}; }}

QProgressBar {{
    background:{BG1}; border:1px solid {GOLD_DARK}; border-radius:4px;
    color:{TEXT}; text-align:center;
}}
QProgressBar::chunk {{
    background:qlineargradient(x1:0,y1:0,x2:1,y2:0, stop:0 {GOLD_DARK}, stop:1 {GOLD});
    border-radius:3px;
}}

QScrollArea {{ border:none; background:transparent; }}
"""


def apply(widget, extra=""):
    """Apply the full Kalandra theme to a widget/dialog (+ optional extras)."""
    widget.setStyleSheet(kalandra_qss() + ("\n" + extra if extra else ""))


def set_gem(button, gem):
    """Tag a QPushButton with a gem accent and refresh its style."""
    button.setProperty("gem", gem if gem in GEMS else "diamond")
    st = button.style()
    st.unpolish(button)
    st.polish(button)


# ---------------------------------------------------------------------------
# 3. PAINTER HELPERS (lazy PyQt) — ornate frame + cut gems
# ---------------------------------------------------------------------------

def _qt():
    """Lazy PyQt import so this module stays importable headless."""
    from PyQt6.QtCore import Qt, QRectF, QPointF
    from PyQt6.QtGui import (QColor, QPen, QBrush, QLinearGradient,
                             QRadialGradient, QPainterPath, QPolygonF)
    return Qt, QRectF, QPointF, QColor, QPen, QBrush, QLinearGradient, \
        QRadialGradient, QPainterPath, QPolygonF


def paint_ornate_frame(painter, rect, radius=12, gems=True, band=3):
    """Draw the layered golden frame inside `rect`.

    Layers (outside -> in): obsidian edge, gold gradient band, bright inner
    hairline. Optionally a cut gem in each corner (ruby TL, sapphire TR,
    emerald BL, diamond BR — the medallion order).
    Call from a paintEvent with antialiasing on.
    """
    (Qt, QRectF, QPointF, QColor, QPen, QBrush, QLinearGradient,
     QRadialGradient, QPainterPath, QPolygonF) = _qt()

    r = QRectF(rect).adjusted(1, 1, -1, -1)

    # 1. obsidian edge
    painter.setPen(QPen(QColor("#05060a"), 2))
    painter.setBrush(Qt.BrushStyle.NoBrush)
    painter.drawRoundedRect(r, radius, radius)

    # 2. gold band (vertical sheen: light top -> dark bottom, like leafed metal)
    g = QLinearGradient(r.topLeft(), r.bottomLeft())
    g.setColorAt(0.0, QColor(GOLD_LIGHT))
    g.setColorAt(0.25, QColor(GOLD))
    g.setColorAt(0.6, QColor(GOLD_DARK))
    g.setColorAt(1.0, QColor(GOLD))
    inner = r.adjusted(band, band, -band, -band)
    painter.setPen(QPen(QBrush(g), band))
    painter.drawRoundedRect(inner, radius - 2, radius - 2)

    # 3. inner hairline
    painter.setPen(QPen(QColor(GOLD_GLOW), 1))
    hl = inner.adjusted(band - 1, band - 1, -(band - 1), -(band - 1))
    painter.drawRoundedRect(hl, radius - 3, radius - 3)

    if gems:
        gr = max(4.0, min(r.width(), r.height()) * 0.018 + 3)
        inset = radius + 2
        corners = [
            ("ruby",     QPointF(r.left() + inset,  r.top() + inset)),
            ("sapphire", QPointF(r.right() - inset, r.top() + inset)),
            ("emerald",  QPointF(r.left() + inset,  r.bottom() - inset)),
            ("diamond",  QPointF(r.right() - inset, r.bottom() - inset)),
        ]
        for name, center in corners:
            draw_gem(painter, center, gr, name)


def draw_gem(painter, center, radius, gem="ruby"):
    """A cut gem: gold bezel, radial-lit body, specular sparkle."""
    (Qt, QRectF, QPointF, QColor, QPen, QBrush, QLinearGradient,
     QRadialGradient, QPainterPath, QPolygonF) = _qt()

    base_hex, light_hex = GEMS.get(gem, GEMS["ruby"])

    # gold bezel ring
    painter.setPen(QPen(QColor(GOLD_DARK), 1.5))
    painter.setBrush(QBrush(QColor(GOLD)))
    painter.drawEllipse(center, radius + 2.5, radius + 2.5)

    # gem body, lit from upper-left
    rg = QRadialGradient(
        QPointF(center.x() - radius * 0.4, center.y() - radius * 0.4),
        radius * 2.1)
    rg.setColorAt(0.0, QColor(light_hex))
    rg.setColorAt(0.55, QColor(base_hex))
    rg.setColorAt(1.0, QColor(base_hex).darker(180))
    painter.setPen(QPen(QColor(base_hex).darker(200), 1))
    painter.setBrush(QBrush(rg))
    painter.drawEllipse(center, radius, radius)

    # facet line + sparkle
    painter.setPen(QPen(QColor(255, 255, 255, 70), 1))
    painter.drawEllipse(center, radius * 0.55, radius * 0.55)
    painter.setPen(Qt.PenStyle.NoPen)
    painter.setBrush(QBrush(QColor(255, 255, 255, 200)))
    painter.drawEllipse(
        QPointF(center.x() - radius * 0.35, center.y() - radius * 0.4),
        radius * 0.18, radius * 0.18)


def draw_orb_dot(painter, center, radius, slug="divine"):
    """Small procedural currency-orb dot (until the W3-03 art kit lands)."""
    (Qt, QRectF, QPointF, QColor, QPen, QBrush, QLinearGradient,
     QRadialGradient, QPainterPath, QPolygonF) = _qt()
    tint = ORB_TINTS.get(slug, ORB_TINTS["divine"])
    rg = QRadialGradient(
        QPointF(center.x() - radius * 0.3, center.y() - radius * 0.35),
        radius * 2.0)
    rg.setColorAt(0.0, QColor("#ffffff"))
    rg.setColorAt(0.35, QColor(tint))
    rg.setColorAt(1.0, QColor(tint).darker(220))
    painter.setPen(QPen(QColor(tint).darker(250), 1))
    painter.setBrush(QBrush(rg))
    painter.drawEllipse(center, radius, radius)


# ---------------------------------------------------------------------------
# 3b. PURE GEOMETRY (used by KalandraWindow; headless-testable)
# ---------------------------------------------------------------------------

def edge_hit_test(x, y, w, h, border=6, corner=14):
    """Which resize edge is under (x, y) in a w×h frameless window?

    Returns one of: 'left','right','top','bottom','topleft','topright',
    'bottomleft','bottomright', or None (not on an edge). Corners use a
    larger zone so diagonal grabs are easy. Pure math — no Qt.
    """
    if w <= 0 or h <= 0 or x < 0 or y < 0 or x > w or y > h:
        return None
    on_l = x <= border
    on_r = x >= w - border
    on_t = y <= border
    on_b = y >= h - border
    # corner zones (bigger targets)
    c_l = x <= corner
    c_r = x >= w - corner
    c_t = y <= corner
    c_b = y >= h - corner
    if (on_t and c_l) or (on_l and c_t):
        return "topleft"
    if (on_t and c_r) or (on_r and c_t):
        return "topright"
    if (on_b and c_l) or (on_l and c_b):
        return "bottomleft"
    if (on_b and c_r) or (on_r and c_b):
        return "bottomright"
    if on_l:
        return "left"
    if on_r:
        return "right"
    if on_t:
        return "top"
    if on_b:
        return "bottom"
    return None


# ---------------------------------------------------------------------------
# 3c. MIRROR WINDOW GEOMETRY (pure math; measured from the actual art)
# ---------------------------------------------------------------------------
# The window art is assets/mirror_frame_square.png — the original mirror
# warped into a squircle (squarer glass, gothic pendant shortened to 45%),
# generated 2026-07-03 per Christian's request. Fractions are relative to
# the CROP below and were computed from the warp's forward map, not guessed.
# (The untouched mirror_of_kalandra.png remains the overlay's own art.)

MIRROR_ART_FILE = "mirror_frame_square.png"   # falls back to the original
MIRROR_ART_CROP = (34, 202, 1871, 1397)       # x, y, w, h on the 1920 canvas
MIRROR_ASPECT = MIRROR_ART_CROP[2] / MIRROR_ART_CROP[3]   # ~1.339 (w / h)

# Face medallions on the top arc (window buttons). Gem colors are IN the art:
# red face = close, blue face = minimize, green face = maximize.
MIRROR_BUTTONS = {
    "close":    (0.1931, 0.2903),   # red-gem face, left
    "minimize": (0.4934, 0.1037),   # blue-gem face, top center
    "maximize": (0.7967, 0.2903),   # green-gem face, right
}
MIRROR_BUTTON_RADIUS = 0.0864       # fraction of window WIDTH

# The star rosette at bottom-right doubles as the resize grip.
MIRROR_RESIZE_GRIP = (0.9297, 0.7036)
MIRROR_GRIP_RADIUS = 0.1127

# Rectangle inscribed in the glass where content lives: below the side
# medallions (so widgets never cover the gold), inside the squircle.
MIRROR_CONTENT = (0.2166, 0.4073, 0.7733, 0.7573)   # x0, y0, x1, y1 fractions

# Where the window title paints (centered), in the open glass between the
# side medallions, just above the content area.
MIRROR_TITLE_Y = 0.330


def mirror_layout(w, h):
    """All hit/layout geometry for a w×h mirror window. Pure math.

    Returns dict with pixel values:
      content -> (x, y, width, height)
      buttons -> {name: (cx, cy, r)}
      grip    -> (cx, cy, r)
      title_y -> int
    """
    w = max(1, int(w)); h = max(1, int(h))
    x0, y0, x1, y1 = MIRROR_CONTENT
    content = (int(w * x0), int(h * y0),
               max(1, int(w * (x1 - x0))), max(1, int(h * (y1 - y0))))
    br = max(6.0, w * MIRROR_BUTTON_RADIUS)
    buttons = {name: (w * fx, h * fy, br)
               for name, (fx, fy) in MIRROR_BUTTONS.items()}
    gx, gy = MIRROR_RESIZE_GRIP
    grip = (w * gx, h * gy, max(8.0, w * MIRROR_GRIP_RADIUS))
    return {"content": content, "buttons": buttons, "grip": grip,
            "title_y": int(h * MIRROR_TITLE_Y)}


def mirror_hit(w, h, x, y):
    """What's under (x, y)? -> 'close'|'minimize'|'maximize'|'grip'|None.

    The CONTENT AREA always wins: the side medallions bleed into the glass
    corners, and a stray click inside your content must never close the
    window. The outer half of each medallion (including its center) remains
    clickable."""
    lay = mirror_layout(w, h)
    cx0, cy0, cw, ch = lay["content"]
    if cx0 <= x <= cx0 + cw and cy0 <= y <= cy0 + ch:
        return None
    for name, (cx, cy, r) in lay["buttons"].items():
        if (x - cx) ** 2 + (y - cy) ** 2 <= r * r:
            return name
    cx, cy, r = lay["grip"]
    if (x - cx) ** 2 + (y - cy) ** 2 <= r * r:
        return "grip"
    return None


# ---------------------------------------------------------------------------
# 3d. FRAME WINDOW GEOMETRY (Christian's Photoshop assets, 2026-07-03)
# ---------------------------------------------------------------------------
# assets/Window.png: square celtic-gold frame, glass inside. Border measured
# programmatically: L140 R145 T128 B137 on a 1461x1490 canvas -> nine-slice
# with a 150px source border. Buttons are separate art (Close.png red gem,
# Minimize.png green gem, Maximize.png blue gem) drawn top-right in the glass.

FRAME_ART_FILE = "Window.png"
FRAME_BTN_FILES = {"close": "Close.png", "minimize": "Minimize.png",
                   "maximize": "Maximize.png"}
FRAME_SRC_BORDER = 150      # px of border in the SOURCE art (nine-slice cut)
FRAME_DST_BORDER = 44       # px the border renders at on screen
FRAME_EDGE = 10             # outermost px that act as resize grips
FRAME_BTN_SIZE = 38         # rendered medallion button diameter
FRAME_BTN_GAP = 8
FRAME_TITLE_STRIP = 46      # glass strip under the top border (title + buttons)


def frame_layout(w, h, border=FRAME_DST_BORDER, btn=FRAME_BTN_SIZE,
                 gap=FRAME_BTN_GAP):
    """Layout for a w×h frame window. Pure math.

    The medallion buttons OVERLAY the top gold border (like a normal
    window's title-bar buttons), vertically centered on the border band and
    right-aligned. The whole glass below the border belongs to content.

    Returns dict:
      content -> (x, y, width, height)          the glass, minus padding
      buttons -> {name: (cx, cy, r)}            minimize, maximize, close (L→R)
      title   -> (x, y)                         title text anchor (on the border)
      strip_h -> bottom of the drag strip (== border)
    """
    w = max(1, int(w)); h = max(1, int(h))
    r = btn / 2.0
    cy = border / 2.0                       # centered ON the border band
    cx_close = w - 14 - r                   # tucked to the top-right corner
    cx_max = cx_close - btn - gap
    cx_min = cx_max - btn - gap
    buttons = {"minimize": (cx_min, cy, r), "maximize": (cx_max, cy, r),
               "close": (cx_close, cy, r)}
    pad = 10
    content = (border + pad, border + pad,
               max(1, w - 2 * (border + pad)),
               max(1, h - 2 * (border + pad)))
    return {"content": content, "buttons": buttons,
            "title": (border + pad, cy),
            "strip_h": border}


def frame_hit(w, h, x, y, border=FRAME_DST_BORDER, edge=FRAME_EDGE):
    """What's under (x, y) in a frame window?

    -> 'close'|'minimize'|'maximize' | an edge name from edge_hit_test
       (resize) | 'title' (move) | None (content).
    The buttons sit ON the border, so they take priority over the resize
    rim; edges win everywhere else on the rim."""
    lay = frame_layout(w, h, border=border)
    for name, (cx, cy, r) in lay["buttons"].items():
        if (x - cx) ** 2 + (y - cy) ** 2 <= (r + 3) ** 2:
            return name
    e = edge_hit_test(x, y, w, h, border=edge)
    if e:
        return e
    cx0, cy0, cw, ch = lay["content"]
    if cx0 <= x <= cx0 + cw and cy0 <= y <= cy0 + ch:
        return None
    return "title"    # anywhere on the gold border = drag


# ---------------------------------------------------------------------------
# 4. SELF-CHECKS (used by tests/stress_test.py)
# ---------------------------------------------------------------------------

def _hex_ok(c):
    return (isinstance(c, str) and c.startswith("#")
            and len(c) in (4, 7, 9)
            and all(ch in "0123456789abcdefABCDEF" for ch in c[1:]))


def self_check():
    """Cheap invariants: all palette entries are valid hex; QSS is balanced."""
    palette = [GOLD, GOLD_LIGHT, GOLD_DARK, GOLD_GLOW, BG0, BG1, BG2, BG3,
               TEXT, MUTED, FAINT, TEAL, COLOR_WARN]
    palette += [c for pair in GEMS.values() for c in pair]
    palette += list(ORB_TINTS.values())
    bad = [c for c in palette if not _hex_ok(c)]
    qss = kalandra_qss()
    problems = []
    if bad:
        problems.append(f"bad hex: {bad}")
    if qss.count("{") != qss.count("}"):
        problems.append("QSS braces unbalanced")
    if "qlineargradient" not in qss:
        problems.append("QSS lost its gradients")
    for token in ("QPushButton", "QTabBar::tab:selected", "QCheckBox::indicator",
                  "QScrollBar", "QComboBox QAbstractItemView", "QToolTip"):
        if token not in qss:
            problems.append(f"QSS missing rule for {token}")
    return problems
